# Original idea by @ISnackable. Thanks to him for handling the hardest parts!
# https://github.com/ISnackable/CercubePlus/blob/main/.github/workflows/Build.yml

name: Build uYouPlus

on:
  workflow_call:
    inputs:
      build_ipa:
        description: "Build package for sideloading"
        type: boolean
      build_debs:
        description: "Build packages for jailbroken devices"
        type: boolean
      sdk_version:
        description: "iOS SDK version to be used during build"
        default: "15.5"
        type: string
      youtube_version:
        description: "The version of YouTube"
        type: string
      uyou_version:
        description: "The version of uYou"
        type: string
      uyouplus_version:
        description: "The version of uYouPlus"
        type: string
        required: true
      decrypted_youtube_url:
        description: "The direct URL to the decrypted YouTube ipa"
        type: string
      create_release:
        description: "Create a draft release"
        type: boolean
      bundle_id:
        description: "Modify the bundle ID. Not recommended"
        default: "com.google.ios.youtube"
        type: string
      app_name:
        description: "Modify the name of the app on the Home Screen. Not recommended"
        default: "YouTube"
        type: string

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build uYouPlus
    runs-on: macos-12
    permissions:
      contents: write

    steps:
      # Symlinked .gitconfig causes issues
      - name: Check for symlinked global .gitconfig
        if: ${{ env.ACT }}
        run: '! readlink $HOME/.gitconfig'

      - name: Change Xcode version
        if: ${{ !env.ACT }}
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '13.4.1'

      - name: Check for Homebrew
        if: ${{ env.ACT }}
        run: command -v brew

      - name: Install Dependencies
        run: brew install ldid xz dpkg make svn wget

      - name: Set PATH environment variable
        run: echo "$(brew --prefix make)/libexec/gnubin" >> $GITHUB_PATH 

      - name: Checkout Main
        uses: actions/checkout@v3
        with:
          path: main
          submodules: recursive

      - name: Setup Theos
        uses: actions/checkout@v3
        with:
          repository: theos/theos
          ref: master
          path: theos
          submodules: recursive

      - name: Setup Theos Jailed
        if: ${{ inputs.build_ipa }}
        uses: actions/checkout@v3
        with:
          repository: qnblackcat/theos-jailed
          ref: master
          path: theos-jailed
          submodules: recursive

      - name: Install Theos Jailed
        if: ${{ inputs.build_ipa }}
        run: |
          ./theos-jailed/install
        env:
          THEOS: ${{ github.workspace }}/theos

      - name: SDK Caching
        id: SDK
        uses: actions/cache@v3
        env:
          cache-name: iOS-${{ inputs.sdk_version }}-SDK
        with:
          path: theos/sdks/
          key: ${{ env.cache-name }}
      
      - name: Download iOS SDK
        if: steps.SDK.outputs.cache-hit != 'true'
        run: |
          svn checkout -q https://github.com/xybp888/iOS-SDKs/trunk/iPhoneOS${{ inputs.sdk_version }}.sdk
          mv *.sdk $THEOS/sdks
        env:
          THEOS: ${{ github.workspace }}/theos

      - name: IPA Caching
        if: ${{ inputs.build_ipa }}
        id: IPA
        uses: actions/cache@v3
        env:
          cache-name: YouTube-${{ inputs.youtube_version }}-IPA
        with:
          path: main/YouTube.ipa
          key: ${{ env.cache-name }}

      - name: Download YouTube IPA
        if: ${{ steps.SDK.outputs.cache-hit != 'true' && inputs.build_ipa }}
        run: |
          wget "$YOUTUBE_URL" --no-verbose -O main/YouTube.ipa && echo -e "==> \033[1mYouTube v${{ inputs.youtube_version }} downloaded! \033[0m"
        env:
          THEOS: ${{ github.workspace }}/theos
          YOUTUBE_VERSION: ${{ inputs.youtube_version }}
          YOUTUBE_URL: ${{ inputs.decrypted_youtube_url }}

      - name: Build .ipa
        if: ${{ inputs.build_ipa }}
        run: |
          cd ${{ github.workspace }}/main
          make package
          echo -e "==> \033[1mSHASUM256: $(shasum -a 256 packages/*.ipa | cut -f1 -d' ')\033[0m"
          echo -e "==> \033[1mBundle ID: ${{ env.BUNDLE_ID }}\033[0m"
        env:
          THEOS: ${{ github.workspace }}/theos
          YOUTUBE_VERSION: ${{ inputs.youtube_version }}
          UYOU_VERSION: ${{ inputs.uyou_version }}
          PACKAGE_VERSION: ${{ inputs.uyouplus_version }}
          BUNDLE_ID: ${{ inputs.bundle_id }}
          DISPLAY_NAME: ${{ inputs.app_name }}
          FINALPACKAGE: ${{ inputs.create_release }}
          IPA: YouTube.ipa

      - name: Build .debs
        if: ${{ inputs.build_debs }}
        run: |
          cd ${{ github.workspace }}/main
          make package
          make clean package THEOS_PACKAGE_SCHEME=rootless
        env:
          THEOS: ${{ github.workspace }}/theos
          JAILBROKEN: 1
          PACKAGE_VERSION: ${{ inputs.uyouplus_version }}
          FINALPACKAGE: ${{ inputs.create_release }}

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        env:
          YOUTUBE_VERSION: ${{ inputs.youtube_version }}
          UYOU_VERSION: ${{ inputs.uyou_version }}
          PACKAGE_VERSION: ${{ inputs.uyouplus_version }}
        with:
          name: uYouPlus_${{ env.YOUTUBE_VERSION }}-${{ env.UYOU_VERSION }}-${{ env.PACKAGE_VERSION }}
          path: ${{ github.workspace }}/main/packages/*
          if-no-files-found: error

      - name: Create Release
        if: ${{ !env.ACT && inputs.create_release }}
        id: create_release
        uses: softprops/action-gh-release@v0.1.15
        env:
          YOUTUBE_VERSION: ${{ inputs.youtube_version }}
          UYOU_VERSION: ${{ inputs.uyou_version }}
          PACKAGE_VERSION: ${{ inputs.uyouplus_version }}
        with:
          tag_name: v${{ env.YOUTUBE_VERSION }}-${{ env.UYOU_VERSION }}-${{ env.PACKAGE_VERSION }}-(${{ github.run_number }})
          name: v${{ env.YOUTUBE_VERSION }}-${{ env.UYOU_VERSION }}-${{ env.PACKAGE_VERSION }}-(${{ github.run_number }})
          files: main/packages/*
          draft: true
